-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 15:38:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente_PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_PF` (
  `id_cliente_pf` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_cliente_pf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_PJ` (
  `id_cliente_pj` INT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  ` cnpj` VARCHAR(18) NULL,
  `razao_social` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cliente_pj`),
  UNIQUE INDEX ` cnpj_UNIQUE` (` cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `id_pagamento` INT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL,
  `tipo_pagamento` VARCHAR(45) NULL,
  `detalhes` JSON NULL,
  PRIMARY KEY (`id_pagamento`, `id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `id_entrega` INT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `codigo_rastreio` VARCHAR(50) NULL,
  `status_entrega` ENUM('Em trânsito', 'Entregue', 'Atrasado') NULL,
  PRIMARY KEY (`id_entrega`, `id_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` Item_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` Item_Pedido` (
  `id_item_pedido` INT NULL AUTO_INCREMENT,
  `id_pedido` VARCHAR(45) NULL,
  `id_produto` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id_item_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id_pedido` INT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `status_pedido` ENUM('Processando', 'Enviado', 'Entregue', 'Cancelado') NOT NULL,
  `Entrega_id_entrega` INT NOT NULL,
  `Entrega_id_pedido` INT NOT NULL,
  ` Item_Pedido_id_item_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_cliente`),
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_id_entrega` ASC, `Entrega_id_pedido` ASC) VISIBLE,
  INDEX `fk_Pedido_ Item_Pedido1_idx` (` Item_Pedido_id_item_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_id_entrega` , `Entrega_id_pedido`)
    REFERENCES `mydb`.`Entrega` (`id_entrega` , `id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_ Item_Pedido1`
    FOREIGN KEY (` Item_Pedido_id_item_pedido`)
    REFERENCES `mydb`.` Item_Pedido` (`id_item_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('PF', 'PJ') NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `Cliente_PF_id_cliente_pf` INT NOT NULL,
  `Cliente_PJ_id_cliente_pj` INT NOT NULL,
  `Pagamento_id_pagamento` INT NOT NULL,
  `Pagamento_id_cliente` INT NOT NULL,
  `Pedido_id_pedido` INT NOT NULL,
  `Pedido_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente_PF_idx` (`Cliente_PF_id_cliente_pf` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente_PJ1_idx` (`Cliente_PJ_id_cliente_pj` ASC) VISIBLE,
  INDEX `fk_Cliente_Pagamento1_idx` (`Pagamento_id_pagamento` ASC, `Pagamento_id_cliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Pedido1_idx` (`Pedido_id_pedido` ASC, `Pedido_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cliente_PF`
    FOREIGN KEY (`Cliente_PF_id_cliente_pf`)
    REFERENCES `mydb`.`Cliente_PF` (`id_cliente_pf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Cliente_PJ1`
    FOREIGN KEY (`Cliente_PJ_id_cliente_pj`)
    REFERENCES `mydb`.`Cliente_PJ` (`id_cliente_pj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Pagamento1`
    FOREIGN KEY (`Pagamento_id_pagamento` , `Pagamento_id_cliente`)
    REFERENCES `mydb`.`Pagamento` (`id_pagamento` , `id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Pedido1`
    FOREIGN KEY (`Pedido_id_pedido` , `Pedido_id_cliente`)
    REFERENCES `mydb`.`Pedido` (`id_pedido` , `id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id_produto` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `descricao` LONGTEXT NULL,
  `preco` DECIMAL(10,2) NULL,
  ` Item_Pedido_id_item_pedido` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_Produto_ Item_Pedido1_idx` (` Item_Pedido_id_item_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_ Item_Pedido1`
    FOREIGN KEY (` Item_Pedido_id_item_pedido`)
    REFERENCES `mydb`.` Item_Pedido` (`id_item_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
